### ISSUE TITLE
request change in reboot menu

### ISSUE THREAD

**Issue by yucellmustafa** [xiaomi-sm6150/android_device_xiaomi_sm6150-common#2]
https://github.com/xiaomi-sm6150/android_device_xiaomi_sm6150-common/blob/lineage-21/overlay-lineage/lineage-sdk/lineage/res/res/values/config.xml#L31

It makes more sense to have systemui instead of fastbootd here.

**Comment by basamaryan** [comment]
https://github.com/LineageOS/android_lineage-sdk/blob/lineage-21.0/sdk/src/java/org/lineageos/internal/util/PowerMenuConstants.java#L37-L43 and it does not make "more sense" having systemui there.

**Comment by yucellmustafa** [comment]
sorry systemui was available on crdroid. That's why I thought it was available there too.
